Agri-Energy Prototype Project/Controllers/CollaborationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agri_Energy_Prototype_Project.Controllers
{
    public class CollaborationsController : Controller
    {
        public CollaborationsController() { }

        public ActionResult Collaborations ()
        {
            return(View());
        }
        // GET: Collaborations
        public ActionResult Index()
        {
            return View();
        }

        // GET: Collaborations/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Collaborations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Collaborations/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Collaborations/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Collaborations/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Collaborations/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Collaborations/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Agri-Energy Prototype Project/Controllers/EducationalResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agri_Energy_Prototype_Project.Controllers
{
    /// <summary>
    /// All method creations below occured after a view template 
    /// was chosen and is based on the Educational Resources's model
    /// </summary>
    public class EducationalResourcesController : Controller
    {
        public ActionResult EducationalResources()
        {
           

            return View();
        }
        // GET: EducationalResources
        public ActionResult Index()
        {
            return View();
        }

        // GET: EducationalResources/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EducationalResources/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EducationalResources/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EducationalResources/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EducationalResources/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EducationalResources/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EducationalResources/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Agri-Energy Prototype Project/Controllers/GreenEnergyMarketplaceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Agri_Energy_Prototype_Project.Controllers
{
    /// <summary>
    /// All method creations below occured after a view template 
    /// was chosen and is based on the GreenEnergyMarketplace's model
    /// </summary>
    public class GreenEnergyMarketplaceController : Controller
    {
        //------------generated after the asp.net framework mvc web application was chosen-----
        public ActionResult GreenEnergyMarketplace ()
        {
            return View();
        }
        // GET: GreenEnergyMarketplace
        public ActionResult Index()
        {
            return View();
        }
//------------generated after the asp.net framework mvc web application was chosen-----
        
        // GET: GreenEnergyMarketplace/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

//------------generated after the asp.net framework mvc web application was chosen-----
        //GET: GreenEnergyMarketplace/Create
        public ActionResult Create()
        {
            return View();
        }
//------------generated after the asp.net framework mvc web application was chosen-----
        // POST: GreenEnergyMarketplace/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                /*
                // Extract data from the form collection
                var greenMarketProvider = collection["GreenMarketProvider"];
                var solutionName = collection["SolutionName"];
                var solutionDescription = collection["SolutionDesription"];

                // Create an instance of your data model (assuming CollaborationModel is your EF entity)
                var collaboration = new CollaborationModel
                {
                    GreenMarketProvider = greenMarketProvider,
                    SolutionName = solutionName,
                    SolutionDesription = solutionDescription
                };

                // Save to the database 
                dbContext.Collaborations.Add(collaboration);
                dbContext.SaveChanges();

                // Redirect to the Index action after successful insertion*/
                return RedirectToAction("Index");
            
            }
            catch
            {
                return View();
            }
        }
//------------generated after the asp.net framework mvc web application was chosen-----
        // GET: GreenEnergyMarketplace/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GreenEnergyMarketplace/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
               

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
//------------generated after the asp.net framework mvc web application was chosen-----
        // GET: GreenEnergyMarketplace/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

//------------generated after the asp.net framework mvc web application was chosen-----
        // POST: GreenEnergyMarketplace/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
               

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Agri-Energy Prototype Project/Controllers/SustainableFarmingHUBController.cs
using Agri_Energy_Prototype_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;



namespace Agri_Energy_Prototype_Project.Controllers
{
    public class SustainableFarmingHUBController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ActionResult SustainableFarmingHUB()
        {
            SustainableFarmingHUB model = new SustainableFarmingHUB();
            ViewBag.Products = _context.SustainableFarmingHUB.ToList();
            return View("ViewProducts", model);

            // model.ViewProducts = _context.SustainableFarmingHUBs.ToList();
            // or whatever your data source is

            //return View();
        }

      


        public SustainableFarmingHUBController()
        {
            _context = ApplicationDbContext.Create();
        }

        // GET: SustainableFarmingHUB
        public ActionResult Index()
       {
            return View();
        }

        // GET: SustainableFarmingHUB/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SustainableFarmingHUB/Create
        [HttpPost]
        public ActionResult Create(SustainableFarmingHUB model)
        {
            if (ModelState.IsValid)
            {
                var newProduct = new SustainableFarmingHUB
                {
                    ProductName = model.ProductName,
                    ProductionDate = model.ProductionDate,
                    ProductionDetails = model.ProductionDetails,
                    ProductUsage = model.ProductUsage,
                    Owner = model.Owner,
                    Category = model.Category
                };
                _context.SustainableFarmingHUB.Add(newProduct);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: SustainableFarmingHUB/Delete/5
        public ActionResult Delete(int id)
        {
            var product = _context.SustainableFarmingHUB.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: SustainableFarmingHUB/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            var product = _context.SustainableFarmingHUB.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            _context.SustainableFarmingHUB.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: SustainableFarmingHUB/Edit/5
        public ActionResult Edit(int id)
        {
            var product = _context.SustainableFarmingHUB.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: SustainableFarmingHUB/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, SustainableFarmingHUB model)
        {
            if (ModelState.IsValid)
            {
                var product = _context.SustainableFarmingHUB.Find(id);
                if (product == null)
                {
                    return HttpNotFound();
                }
                product.ProductName = model.ProductName;
                product.ProductionDate = model.ProductionDate;
                product.ProductionDetails = model.ProductionDetails;
                product.ProductUsage = model.ProductUsage;
                product.Owner = model.Owner;
                product.Category = model.Category;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public ActionResult ViewProducts()
        {
            // Retrieve the saved data from the database or repository
            var products =_context.SustainableFarmingHUB.ToList(); // Assuming you have a database context or repository

            return View(products);
        }

    }
}

Agri-Energy Prototype Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        @ViewBag.Title = "Agri-Energy Connect"
    </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        /* Custom styles for the navigation bar */
        .navbar-dark {
            background-color: #4CAF50; /* Green color */
        }

            .navbar-dark .navbar-nav > li > a {
                color: #ffffff; /* White color */
            }

                .navbar-dark .navbar-nav > li > a:hover {
                    color: #f0f0f0; /* Light gray color on hover */
                }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Agri-Energy Connect Services", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    @Html.ActionLink("Agri-Energy Connect", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Educational Resources", "EducationalResources", "EducationalResources", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Project Collaborations", "Collaborations", "Collaborations", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Sustainable Farming HUB", "SustainableFarmingHUB", "SustainableFarmingHUB", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Green Energy Marketplace", "GreenEnergyMarketplace", "GreenEnergyMarketplace", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Agri-Energy Connect</p>

        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>